//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Transactions')
export class TransactionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('real', { nullable: true })
  amount: number;

  @Column('integer', { nullable: true })
  sender: number;

  @Column('integer', { nullable: true })
  receiver: number;

  @Column('date', { nullable: true })
  transactionDate: Date;

  @Column('integer', { nullable: true })
  paymentMethod: number;
}
