//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Users')
export class UsersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  email: string;

  @Column('text', { nullable: true })
  phoneNumber: string;

  @Column('bool', { nullable: true })
  subscriptionStatus: boolean;

  @Column('date', { nullable: true })
  registrationDate: Date;

  @Column('text', { nullable: true })
  password: string;
}
