//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="PayPal for Papua New Guinea" />
    <CardContent>
      a digital payment platform designed for users in Papua New Guinea,
      enabling secure transactions and supporting multiple payment methods
      including PayPal, CashApp, and Visa. It aims to facilitate easy and secure
      money transfers both locally and internationally.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
